package:
  name: pyside-tools
  version: 0.2.15

source:
  fn: 0.2.15.tar.gz
  url: https://github.com/PySide/Tools/archive/0.2.15.tar.gz

requirements:
  build:
    - cmake
    - qt
    - python
    - pyside
  run:
    - qt
    - python
    - pyside

build:
  number: 0

#test:
#  commands:
#    - shiboken --help
#  imports:
#    - shiboken

about:
    home: https://github.com/PySide/Tools
    license: LGPL
