package:
  name: occt
  version: 7.0.0

build:
  number: 2

source:
  path: ../../../tmp/occt

requirements:
  build:
    - ninja       [win]
    - python
    - freetype
    - vtk 7.0.0
  run:

about:
  summary: occt
