package:
    name: freecad_debug
    version: 0.17

build:
    number: 0

    features:
        - vc14  # [win and py>=35]
        - occt7.1.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.1.0

requirements:
    build:
        - nomkl  # [unix]
        - toolchain
        - ninja  # [win]
        - vc 14  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.*
        - pyside
        - occt
        - netgen
        - vtk 7.*
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
    run:
        - vc 14  # [win and py>=35]
        - boost
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.*
        - pyside
        - occt
        - netgen
        - vtk 7.*
        - libmed
        - xerces-c
        - zlib 1.2*
about:
    summary: freecad

