package:
    name: freecad
    version: 0.17

build:
    number: 11

source:
    git_url: https://github.com/FreeCAD/FreeCAD
    git_tag: master

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp 1.66.0
        - pybind11  # [unix]
        - boost 1.66.0  # [win]
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 5.6.*
        - pyside2  2.0.0.dev0 py36_0  # [unix]
        - pyside2  2.0.0.dev0 py36_vc14_0  # [win]
        - occt 7.2.0
        - netgen
        - vtk 8.1.*
        - libmed
        - hdf5
        - xerces-c 3.2.*
        - zlib 1.2.*
        - doxygen
        - git
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp 1.66.0
        - boost 1.66.0  # [win]
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.6.*
        - pyside2
        - occt 7.2.0
        - netgen
        - vtk 8.1.*
        - libmed
        - xerces-c 3.2.*
        - zlib 1.2*
        - git
        - calculix  # [unix]
about:
    summary: freecad

