package:
    name: freecad
    version: 0.17

build:
    number: 1

source:
    git_url: https://github.com/FreeCAD/FreeCAD
    git_tag: master

    patches:
        # - none

requirements:
    build:
        - cmake
        - swig
        - shiboken
        - eigen 3.3
        - hdf5
        - boost-cpp 1.63.0
        - python
        - matplotlib
        - coin
        - pivy
        - qt 4.8.7 7
        - pyside
        - pyside-tools
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
    run:
        - boost-cpp 1.63.0
        - python
        - numpy
        - matplotlib
        - coin
        - pivy
        - qt 4.8.7 7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
about:
    summary: freecad

