package:
    name: freecad
    version: 0.17

build:
    number: 4

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: py3-24

    patches:
        - cmake.patch
        - coin.patch
        - netgen.patch
        - xerces.patch

    features:
        - vc14  # [win and py>=35]

    track_features:
        - vc14  # [win and py>=35]
        - occt7.1.0

requirements:
    build:
        - toolchain
        - ninja  # [win]
        - vc 14  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp 1.63.*
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp 1.63.*
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
        - zlib 1.2*
about:
    summary: freecad

