package:
    name: pyocct
    version: 0.0.1

# source:
#     git_url: https://github.com/looooo/pyOCCT
#     git_tag: master

build:
    number: 0
    features:
        - vc14  # [win]

requirements:
    build:
        - toolchain
        # - gcc  # [win]
        - cmake
        - ninja  # [win]
        - vc 14  # [win and py>=35]
        - python
        - pybind11 2.3.0
        - occt 7.2.0
        - smesh
        - vtk
        - netgen
    run:
        - vc 14  # [win and py>=35]
        # - libgcc  # [linux]
        - python
        - occt 7.2.0
        - smesh
        - vtk
        - netgen

test:
    imports:
        - OCCT

about:
    summary: python bindings to OCCT
