package:
    name: pivy
    version: 0.6.3

source:
    git_url: https://github.com/looooo/pivy
    git_tag: master

    patches:
        - no_soqt.patch

build:
    string: py35_dev_0 # [py==35]
    string: py36_dev_0 # [py==36]
    string: py27_dev_0 # [py==27]
    features:
        - vc14  # [win]
        - nosoqt

    track_features:
        - vc14  # [win]
        - nosoqt
  
requirements:
    build:
        - python
        - swig 3.0.8
        - coin3d
        - vc 14  # [win]
        - colorama
        # - soqt
    run:
        - python
        - coin3d
        # - soqt
        - vc 14  # [win]

test:
    imports:
        - pivy.coin
        # - pivy.gui.soqt

about:
    home: https://github.com/looooo/pivy
    license: ISC License
    license_family: BSD
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/looooo/pivy
    dev_url: https://github.com/looooo/pivy

extra:
    recipe-maintainers:
        - looooo
