package:
  name: pivy
  version: 0.6.0

build:
  number: 0

source:
  git_url: https://github.com/looooo/pivy
  
requirements:
  build:
    - python
    - swig
    - coin
  run:
    - python
    - coin

about:
  summary: python buindings to coin
