package:
  name: coin
  version: 4.0.0

build:
  string: cmake
  number: 0

source:
  # not working with conda right now
  # clone manually to make the build and place the recipe in
  # coin/packageing/conda

  hg_url: https://bitbucket.org/Coin3D/coin/CMake
  # hg_tag: CMake

  # path: ../../



requirements:
  build:
    - mercurial
    - cmake

about:
  summary: coin3d
