package:
  name: netgen
  version: 6.1

build:
  number: 4

source:
  git_url: https://github.com/looooo/netgen
  git_tag: master

requirements:
  build:
    - cmake
    - occt
    - tk
  run:
    - occt
    - tk

about:
  summary: netgen
