package:
  name: coin
  version: 4.0.0

build:
  string: cmake_2
  number: 1

source:
  # not working with conda right now
  # clone manually to make the build and place the recipe in
  # coin/packageing/conda

  path: ../../../tmp/coin

  # hg_url: https://bitbucket.org/Coin3D/coin
  # hg_tag: CMake

about:
  summary: coin3d
