package:
    name: freecad-debug
    version: 0.17

build:
    number: 12
    features:
        - vc14  # [win and py>=35]

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp 1.66.0
        - pybind11
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 5.6.*
        - pyside2 5.6.*
        - occt 7.2.0
        - netgen  # [not win32]
        - libmed  # [not win32]
        - vtk 8.1.*
        - hdf5
        - xerces-c 3.2.*
        - zlib 1.2.*
        - doxygen
        - git
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp 1.66.0
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.6.*
        - pyside2 5.6.*
        - occt 7.2.0
        - netgen  # [not win32]
        - libmed  # [not win32]
        - vtk 8.1.*
        - xerces-c 3.2.*
        - zlib 1.2*
        - git
        - calculix  # [unix]
about:
    summary: freecad


about:
    summary: freecad
