package:
    name: soqt
    version: 1.7.0

source:
    fn: soqt.tar.gz
    url: https://github.com/looooo/pivy/releases/download/v0.6.1-0/soqt.tar.gz
    sha256: a2e852d9a6949628d96f23b1fa2bf01b9ef36c880c1397b433bae10f704aeae6

    patches:

build:
    number: 0
    skip: true  # [py<35]

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]

requirements:
    build:
        - vc 14  # [win]
        - ninja  # [win]
        - cmake
        - qt 4.8.7
        - coin3d
    run:
        - vc 14  # [win]
        - qt 4.8.7
        - coin3d

about:
    home: https://bitbucket.org/Coin3D/soqt
    # license: BSD 3-Clause
    # license_family: BSD
    # license_file: COPYING
    summary: Simage, image-library needed by Cin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
